apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: argocd-demo
  region: us-west-2
  version: "1.18"

managedNodeGroups:
  - name: argocd-demo-ng
    instanceType: t3.medium
    minSize: 1
    maxSize: 4
    desiredCapacity: 3
